modLoader = "javafml"
loaderVersion = "[${forgeMinVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeMinVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejsVersion},)"
ordering = "NONE"
side = "BOTH"
