group = com.almostreliable
license = GNU Lesser General Public License v3.0

# Mod options
modId = morejs
modName = MoreJS
modVersion = 0.13.1
modAuthor = AlmostReliable
modDescription = More KubeJS stuff.

# Common
minecraftVersion = 1.21
neoforgeVersion = 21.0.167
kubejsVersion = 2100.7.0-build.119

# AlmostGradle
almostgradle.launchArgs.resizeClient = true
almostgradle.launchArgs.autoWorldJoin = true

almostgradle.recipeViewers.emi.version = 1.1.12
almostgradle.recipeViewers.emi.minecraftVersion = 1.21

# Parchment
neoForge.parchment.minecraftVersion = 1.21
neoForge.parchment.mappingsVersion = 2024.07.07

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

