group = com.almostreliable.mods
license = GNU Lesser General Public License v3.0
loom.platform = neoforge

# Mod options
modPackage = com.almostreliable.morejs
modId = morejs
modName = MoreJS
modVersion = 0.10.0
modAuthor = AlmostReliable
modDescription = More KubeJS stuff.

# Common
minecraftVersion = 1.21
neoforgeVersion = 21.0.6-beta
kubejsVersion = 2100.7.0-build.79

# Github
githubUser = AlmostReliable
githubRepo = morejs

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

