group = com.almostreliable
license = GNU Lesser General Public License v3.0

# Mod options
modId = morejs
modName = MoreJS
modVersion = 0.15.0
modAuthor = AlmostReliable
modDescription = More KubeJS stuff.

# Common
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.209
kubejsVersion = 2101.7.2-build.264

# AlmostGradle
almostgradle.launchArgs.resizeClient = true
almostgradle.launchArgs.autoWorldJoin = true

almostgradle.recipeViewers.emi.version = 1.1.22
almostgradle.recipeViewers.emi.minecraftVersion = 1.21.1

# Parchment
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

