@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.missingname;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
