@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.missingname.modules;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
